# define global constant for model

from pathlib import Path

DATASET_PATH = Path('../GTSRB')
DATASET_PATH_GTSDB = Path('../GTSDB')

LABELS_PATH_TEST  = DATASET_PATH.joinpath('Test.csv')
LABELS_PATH_TRAIN = DATASET_PATH.joinpath('Train.csv')



IMGS_PATH_TEST_GTSDB  = DATASET_PATH_GTSDB.joinpath('Test')
IMGS_PATH_TRAIN_GTSDB = DATASET_PATH_GTSDB.joinpath("Train")
LABELS_PATH_TRAIN_GTSDB = IMGS_PATH_TRAIN_GTSDB.joinpath('Train.csv')
LABELS_PATH_TEST_GTSDB = '.'
IMGS_PATH_TEST = DATASET_PATH
IMGS_PATH_TRAIN = DATASET_PATH
NUM_CLASSES = 43
